nirs/kubectl-gather

go.mod
go.sum
pkg/gather/agent.go

- Restart watching after recoverable errors
- Stop watcher when done, fix resource leak
- Handle the unlikely case when the pod is running when receiving an Added event
- Return error (hopefully) helpful error when watching fail instead of logging a warning and timeout out
- Improve names
- Tidy go.mod - gather direct and indirect packages

Improve robustness and correctness of waiting for agent pod

---

pkg/gather/logs.go

- Skip invalid container status, so we can gather some logs from the pod
- Logs warnings for invalid container status

Improve error handling when listing containers

---

pkg/gather/gather.go

Previously we flattened the output to "resource.group" or "resource" (when group is empty). Now we gather resources with a non-empty group under the "group" directory.
This makes the output more compatible with `oc adm must-gather`, but it not the same, since must-gather output is inconsistent. In some cases it creates a fake "core" directory for resources with empty group.
Example output:
$ tree -L 4 gather-all/dr1/namespaces/open-cluster-management-agent
gather-all/dr1/namespaces/open-cluster-management-agent
├── apps
│   ├── deployments
│   │   ├── klusterlet-registration-agent.yaml
│   │   └── klusterlet-work-agent.yaml
│   └── replicasets
│       ├── klusterlet-registration-agent-589d97cd97.yaml
│       ├── klusterlet-work-agent-54df7bf9d9.yaml
│       └── …

Group resources by group

---

pkg/gather/addons.go

Addons register now "group/resource" instead of "resource.group".

Fix rook addon registry entry

---

pkg/gather/gather.go

Since b3c69124635, the found namespaces were not stored in the right namespaces list, so we always collected all namespaces.

Fix namespaces validation

---

Makefile
README.md
cmd/local.go
cmd/remote.go
cmd/root.go
pkg/gather/addons.go
pkg/gather/gather.go

This is useful when you don't want to gather pod logs or rook commands and debug logs from the nodes. It will be more useful when we have more addons, and allow making some addons optional.

Support enabling only specific addons

---

cmd/root.go
pkg/gather/addons.go

Added availables addons list to the example.
E.g.
```
--addons strings       if specified, comma separated list of addons to enable (available addons: logs, rook)
```

Available addons list

---

pkg/gather/addons.go
pkg/gather/backend.go
pkg/gather/gather.go
pkg/gather/logs.go
pkg/gather/rook.go

Instead of passing 5 arguments to AddonFunc, pass a AddonBackend interface providing function to get the arguments.
The AddonBackend interface extends the Queuer interface so addons can embed the backend and use it to get options, output directory, and queue work. This simplifies the addon types, cleans up the code and make it more uniform.
The motivation is:
- make it easier to create new addons using simpler interfaces
- make addons code easier to understand since existing addons are the example for creating new addons.
- support concurrent gathering eliminating duplicate gathering for the same resource
- make it possible to move addons to a new package by depending on few public gather types and interfaces

Introduce  AddonBackend interface

---

README.md
kubectl_complete-gather

The script can be copied to the PATH to enable shell completion.
Example completions
```
$ kubectl gather --[TAB]
--addons      (if specified, comma separated list of addons to enable (available addons: logs, pvcs, rook))
--contexts    (comma separated list of contexts to gather data from)
--directory   (directory for storing gathered data (default "gather.{timestamp}"))
--help        (help for gather)
--help        (help for kubectl gather)
--kubeconfig  (the kubeconfig file to use)
--namespaces  (if specified, comma separated list of namespaces to gather data from)
--remote      (run on the remote clusters (requires the "oc" command))
--verbose     (be more verbose)
```

Add shell completion helper script

---

Containerfile

Pass ldflags to the container so we build in the same way.

Unify container build ldflags

---

.github/workflows/ci.yaml
Makefile
cmd/remote.go
cmd/root.go
gather
pkg/gather/gather.go

- Eliminate duplicate builds
- Add --version flag reporting the injecting version
- Use actual version in /must-gather/version
- Use the current image version by injecting the image into the executable 
- Generate the version using `git describe` and inject it into the executable

Automate version management

---

CONTRIBUTING.md

The container image can be used on amd64 and arm64 hosts.

Update CONTRIBUTING - container is multi-arch now

---

.gitignore
e2e/Makefile
e2e/clusters/clusters.go
e2e/cmd/main.go
e2e/commands/commands.go
e2e/gather_test.go
e2e/go.mod
e2e/go.sum

The e2e module contains a helper tool (e2e) and a test suite (gather_test.go).
The helper tool creates and deletes 2 kind clusters. This takes about 35 seconds, and will likely take more when the cluster are more interesting, so we keep it outside of the test suite. This way we can run tests very quickly with the same cluster. Since the gathering from a cluster is mostly immutable, reusing the same cluster is safe.
Issues:
- The test suite contain one trivial test, gathering both clusters
- Gathered data is not validated yet
- The logs are too noisy. We need to log debug logs only to test log. Normal output should include only the major events.
- Test configurations and gathered output are stored in the e2e directory.  This should move to a temporary test directory.
Example test flow:
$ …

Start e2e tests

---

README.md
cmd/root.go
e2e/gather_test.go

Add --log-format with "text" (default) and "json" options. When using
text format we disable caller info and stacktraces in the console logs
bug keep them enabled in the log file. When using json logs we enable
everything so a program can consume what it needs.
Replace the DevelopmentConfig with ProductionConfig that have nicer keys
(e.g. "level" instead of "L").
Example text logs (default):
% ./kubectl-gather --contexts dr1,dr2,hub --log-format text -d gather.text
2025-01-14T16:33:01.901+0200        INFO    gather  Using kubeconfig "/Users/nir/.kube/config"
2025-01-14T16:33:01.904+0200        INFO    gather  Gathering from all namespaces
2025-01-14T16:33:01.904+0200        INFO    gather  Using all addons
2025-01-14T16:33:01.904+0200        INFO    gather  Gathering from cluster "dr1" …

Machine friendly logs

---

.golangci.yaml
Makefile

Import enabled linters from Cobra.
The new inters revealed few issues, so some linters disabled until we fix the issues.

Add lint target and config file

---

.github/workflows/test.yaml

Describes better the purpose of the workflow, and the name "Test" is more consistent with "Release".

Rename ci workflow to test

---

pkg/gather/gather.go

Recently I see random deadlocks, both in small and big clusters.
Example from last run:
% grep -A1 -E '^goroutine.+chan send' deadlock.log
goroutine 412 [chan send, 3 minutes]:
github.com/nirs/kubectl-gather/pkg/gather.(*WorkQueue).Queue(...)
--
goroutine 411 [chan send, 3 minutes]:
github.com/nirs/kubectl-gather/pkg/gather.(*WorkQueue).Queue(...)
--
goroutine 415 [chan send, 3 minutes]:
github.com/nirs/kubectl-gather/pkg/gather.(*WorkQueue).Queue(...)
--
goroutine 413 [chan send, 3 minutes]:
github.com/nirs/kubectl-gather/pkg/gather.(*WorkQueue).Queue(...)
--
goroutine 414 [chan send, 3 minutes]:
github.com/nirs/kubectl-gather/pkg/gather.(*WorkQueue).Queue(...)
--
goroutine 416 [chan send, 3 minutes]:
github.com/nirs/kubectl-gather/pkg/gather.(*WorkQueue).Queue(...)
We have 6 workers, …

Increase queue size

---

docs/internals.md
pkg/gather/backend.go
pkg/gather/gather.go
pkg/gather/rook.go
pkg/gather/workqueue.go

Eliminate the deadlocks and uncontrolled memory usage by switching to
unbuffered channels. When queuing work, the function returns when one of
the workers picked up the work. If all workers are busy, the caller is
blocked until a worker is available.
Previously we had one work queue, and anyone could queue work on the
queue for later processing without any limit. This caused deadlocks
when al workers are trying to queue work and the queue becomes full.
The new pipeline splits the work to 3 steps:
prepare -> gather -> inspect
Pipeline steps:
1. prepare: look up namespaces and api resources, and queue work on the
gather work queue.
2. gather: run work functions queued by the prepare step, and queue work
on the inspect work queue
3. inspect: run work functions queued by the gather step. …

New gather pipeline

---

.github/workflows/release.yaml

Add a release-container job building and pushing the container to avoid manual builds.
Preview:
- https://github.com/nirs/kubectl-gather/releases/tag/v0.8.1-pre1
- https://quay.io/repository/nirsof/gather?tab=tags
Fixes #42

Build and push container as part of the release

---

.gitignore
e2e/Makefile
e2e/clusters/clusters.go
e2e/gather_test.go

We want to add many more tests and keeping all the files and directories in the e2e/ directory is too messy. All the files are created at out/ now.
Example content after running the tests:
% tree -L2 out
out
├── kind-c1.yaml
├── kind-c2.yaml
├── kubeconfig.yaml
├── test-gather
│   ├── gather.log
│   ├── kind-c1
│   └── kind-c2
└── test-json-logs
├── gather.log
├── kind-c1
└── kind-c2

e2e: Keep generated files under out/

---

.github/workflows/release.yaml
Containerfile
Makefile
e2e/go.mod
e2e/go.sum
go.mod

Using same go and toolchain versions as ramen and ramenctl to make it easy to integrate kubectl-gather in ramen related projects.
Changes:
- Go version is specified once in the go.mod.
- The release workflow uses now go version from the go.mod file (like the test workflow).
- The Makefile set GOTOOLCHAIN=auto to download newer toolchain if needed.
- The Containerfile build stage uses go container with version from go.mod
- The Containerfile build command uses GOTOOLCHAIN=auto to download newer toolchain if needed.
Pre-release for testing: https://github.com/nirs/kubectl-gather/releases/tag/v0.9.0-pre2
Pre-release container for testing: quay.io/nirsof/gather:0.9.0-pre2

go: Update to go 1.24.0

---

e2e/Makefile
e2e/testdata/base/deploy.yaml
e2e/testdata/base/kustomization.yaml
e2e/testdata/base/ns.yaml
e2e/testdata/base/pv.yaml
e2e/testdata/base/pvc.yaml
e2e/testdata/c1/kustomization.yaml
e2e/testdata/c2/kustomization.yaml
e2e/testdata/common/kustomization.yaml

We want to have known data for testing that will not change behind our
back when k8s or kind changes the way stuff is deployed.
We deploy 3 applications:
- common-busybox in namespace test-common, on both clusters
- c1-busybox in namespace test-c1, on cluster c1
- c2-busybox in namespace test-c2, on cluster c2
The deployment it trivial busybox deployment with one pvc.
New deploy and undeploy targets can be used to work on the deployment.
```console
% tree -L3 out/test-gather
out/test-gather
├── gather.log
├── kind-c1
│   ├── cluster
│   │   ├── apiregistration.k8s.io
│   │   ├── flowcontrol.apiserver.k8s.io
│   │   ├── namespaces
│   │   ├── networking.k8s.io
│   │   ├── nodes
│   │   ├── persistentvolumes
│   │   ├── rbac.authorization.k8s.io
│   │   ├── scheduling.k8s.io
│   │   └── …
```

e2e: Deploy applications for testing

---

e2e/clusters/clusters.go
e2e/commands/commands.go
e2e/gather_test.go

Looking at the code after a while, it is not clear how commands are run. Rename commands.LogStderr() to commands.Run() to make it more clear.
Based on #91 for testing.

e2e: Improve commands names

---

e2e/clusters/clusters.go
e2e/gather_test.go
e2e/validate/validate.go

Changes: 
Validate e2e tests:
Add new validate package validation functions
Validate that expected files and directory structures are created correctly
Add JSON log format validation to ensure --log-format=json works as expected
Additional e2e tests:
Namespace-Specific Test: Add e2e test for gathering data from specific namespaces
Test results:
```
=== RUN   TestGather
2025/07/24 13:38:09 Running ../kubectl-gather --contexts kind-c1,kind-c2 --kubeconfig out/kubeconfig.yaml --directory out/test-gather
2025/07/24 13:38:09 2025-07-24T13:38:09.418+0530	INFO	gather	Using kubeconfig "out/kubeconfig.yaml"
2025/07/24 13:38:09 2025-07-24T13:38:09.419+0530	INFO	gather	Gathering from all namespaces
2025/07/24 13:38:09 2025-07-24T13:38:09.419+0530	INFO	gather	Using all addons
2025/07/24 13:38:09 …
```

e2e: Add e2e validation and additional tests

---

e2e/gather_test.go

Changes:
**Cluster node resource:**
- Add `c1ClusterNodes` and `c2ClusterNodes` resource lists to track cluster node files
- Update `TestGather` and `TestGatherEmptyNamespaces` to validate presence and absence of node resources across clusters
```
=== RUN   TestGather
2025/07/25 12:54:41 Running ../kubectl-gather --contexts kind-c1,kind-c2 --kubeconfig out/kubeconfig.yaml --directory out/test-gather
2025/07/25 12:54:42 2025-07-25T12:54:42.689+0530	INFO	gather	Using kubeconfig "out/kubeconfig.yaml"
2025/07/25 12:54:42 2025-07-25T12:54:42.691+0530	INFO	gather	Gathering from all namespaces
2025/07/25 12:54:42 2025-07-25T12:54:42.691+0530	INFO	gather	Using all addons
2025/07/25 12:54:42 2025-07-25T12:54:42.691+0530	INFO	gather	Gathering from cluster "kind-c1"
2025/07/25 12:54:42 …
```

 Add validation for cluster node resources

---

e2e/gather_test.go
e2e/validate/validate.go

Enhance validate.Exist() and validate.Missing to validate multiple resources lists. This removes lot of noise from the tests, dong one call per cluster with all resources lists instead of one call per resources list.

e2e: Validate multiple resources lists

---

cmd/root.go
e2e/gather_test.go
e2e/validate/validate.go

Adds validation to prevent --namespaces="" from gathering no resources. When users specify an empty namespaces, the command now fails with a error message instead of proceeding with unexpected behavior.
Changes:
- Validation Logic: Add validateOptions() function to check for empty namespace flag
e2e:
- Update TestGatherEmptyNamespaces to expect validation error instead of successful execution
- Verify no resources are gathered when validation fails
- Export pathExists function in validate package for direct use in tests
Manual kubectl gather run:
- without --namespaces="" validation, gathers all data:
```
./kubectl-gather --contexts kind-c1,kind-c2 --kubeconfig out/kubeconfig.yaml --namespaces="" --directory out/test-empty-ns
2025-07-29T18:41:39.901+0530	INFO	gather	Using kubeconfig …
```

Validate empty namespaces flag

---

Makefile

Add optional TAG argument to allow building a version using existing image.
Example usage:
% make TAG=test
GO_TOOLCHAIN=auto CGO_ENABLED=0 go build -ldflags="-s -w -X 'github.com/nirs/kubectl-gather/pkg/gather.Version=0.9.0-7-g88fef25' -X 'github.com/nirs/kubectl-gather/pkg/gather.Image=quay.io/nirsof/gather:test'"
If not set we build with the version (current behavior):
% make
GO_TOOLCHAIN=auto CGO_ENABLED=0 go build -ldflags="-s -w -X 'github.com/nirs/kubectl-gather/pkg/gather.Version=0.9.0-7-gce7b1f9' -X 'github.com/nirs/kubectl-gather/pkg/gather.Image=quay.io/nirsof/gather:0.9.0-7-gce7b1f9'"

build: Allow building with existing image

---

README.md
cmd/local.go
cmd/remote.go
cmd/root.go
e2e/gather_test.go
pkg/gather/gather.go
pkg/gather/pvcs.go

- Add `clusterScope` flag to control gathering cluster-scoped resources.
- Add examples in help text for using the `--cluster` flag.
- Implement `validateOptions()` to enforce that empty namespaces can only
be used when cluster scope is enabled and gather all resources if neither
namespaces nor cluster flags are set.
- Document gathering cluster scope resources
-  add test for empty namespaces with --cluster=false
- add tests for --cluster flag combinations
- TestGatherClusterTrue: --cluster=true
- TestGatherClusterFalse: --cluster=false
- TestGatherEmptyNamespacesClusterTrue: --namespaces="" --cluster=true
- TestGatherSpecificNamespacesClusterTrue: specific namespaces + cluster
- TestGatherSpecificNamespacesClusterFalse: specific namespaces only
Fixes #98

add --cluster flag and validate options

---

e2e/output_test.go
pkg/gather/output_reader.go

Return empty slice instead of error when resource directory doesn't exist. This allows callers to handle missing resources without explicit error checking. Also added e2e test covering this case.
e2e:
```
=== RUN   TestOutput/deployment
output_test.go:45: Read deployment "common-busybox"
=== RUN   TestOutput/pods
output_test.go:56: Listed pods ["common-busybox-85888ff8f9-lchrr"]
output_test.go:70: Read pod "common-busybox-85888ff8f9-lchrr"
=== RUN   TestOutput/cluster_scope
output_test.go:82: Listed namespaces ["default" "kube-node-lease" "kube-public" "kube-system" "local-path-storage" "test-c1" "test-common"]
output_test.go:96: Read namespace "default"
output_test.go:96: Read namespace "kube-node-lease"
output_test.go:96: Read namespace "kube-public"
output_test.go:96: Read namespace …
```

Handle non existent dirs in ListResources

---

go.mod

We keep go 1.24.0 to be compatible with downstream consumes of this package. For building ramenctl we should always use latest go version.
With this change we use go 1.25.0 to build for tests, building the executables, and running golangci-lint.

build: Use go 1.25
